import Head from "next/head";
import Counter from "../components/counter";
import Header from "../components/header";
import styled from "styled-components";

const Content = styled.div`
  display: flex;
  flex: 1 1 auto;
  align-items: center;
  justify-content: center;
  height: 100%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content>
        <Counter />
      </Content>
    </>
  );
}
